steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-west2-docker.pkg.dev/$PROJECT_ID/x-account-monitor/x-account-monitor:latest
      - .

images:
  - us-west2-docker.pkg.dev/$PROJECT_ID/x-account-monitor/x-account-monitor:latest

options:
  logging: CLOUD_LOGGING_ONLY
